Feature/world
robo-bootcamp/pyBotic pull request #4
Opened 2020-06-13 01:31 UTC by 00arun00

- updated init to fix imports
- temporary txt map loader (need to change this definitely)
- restructured the project
- partial implementation of world envs
- added a sample txt map file
- added unnitests

2020-06-13 01:45 UTC, 00arun00 commented on .github/workflows/python-package.yml
> +        python-version: [3.6, 3.7, 3.8]
had to remove it since dataclasses are not supported <3.6

2020-06-13 01:45 UTC, 00arun00 commented on pybotic/__init__.py
> +from . import utils
fix importing

2020-06-13 01:45 UTC, 00arun00 commented on pybotic/utils/__init__.py
> +from . import world_utils
fix importing

2020-06-13 01:45 UTC, 00arun00 commented on pybotic/utils/world_utils.py
> +def load_3d_world_map(file_name):
just temp we will re-write this

2020-06-13 01:45 UTC, 00arun00 commented on pybotic/worlds.py
> +                raise ValueError(f"wrong shape {shape_}")
validated the inputs send to the constructor, __post_init__() runs automatically after auto-generated __init__()

2020-06-13 01:45 UTC, 00arun00 commented on pybotic/worlds.py
> +        # can't have pass here for coverage reasons
can't add pass statement here since it will cause problems with coverage so removing it

2020-06-13 01:45 UTC, 00arun00 commented on pybotic/worlds.py
> +        return cls(boundary, obstacles, start, goal)
currently will error out with the current load_3d_world_map() will be fine after that is fixed

2020-06-13 01:45 UTC, 00arun00 commented on setup.py
> -        'Programming Language :: Python :: 3.5',
remove support

2020-06-13 01:45 UTC, 00arun00 commented on tests/sample_world.txt
> +block 0.0 18.0  4.5 10.0 19.0  6.0 120 120 120
sample not frozen can be used for rewriting load_3d_map() 

- probably need to add start and goal to it

2020-06-13 01:45 UTC, 00arun00 commented on tests/test_Continous3D_Static.py
> +class TestContinous3DStatic(unittest.TestCase):
testing continous3dstatic 
Missing tests for :
- create_from_txt_file()

2020-06-13 01:45 UTC, 00arun00 commented on pybotic/worlds.py
> +        return cls(boundary, obstacles, start, goal)
tests are missing currently

2020-06-13 03:00 UTC, 00arun00 commented on pybotic/worlds.py
> +        # can't have pass here for coverage reasons
https://www.codependentcodr.com/code-quality-challenge-1-test-coverage.html

2020-06-13 03:57 UTC, gunjanpatil requested changes

2020-06-13 03:57 UTC, gunjanpatil commented on pybotic/worlds.py
> +                raise ValueError(f"wrong shape {shape_}")
add automated conversion to suggested shapes and types

2020-06-13 03:57 UTC, gunjanpatil commented on pybotic/worlds.py
> +    _goal: np.ndarray = field(default=None)
Change type from np.ndarray to node based structure

2020-06-13 03:57 UTC, gunjanpatil commented on pybotic/worlds.py
> +                Obstacle_state: (numpy.ndarray) state/location of obstacles
Fix the order of keys returned in the dict

2020-06-13 03:57 UTC, gunjanpatil commented on pybotic/worlds.py
> +        self._robot_pose = robot_action
add automated conversion to suggested shapes and types

2020-06-13 03:57 UTC, gunjanpatil commented on pybotic/worlds.py
> +                robot_action: (iterable 3d) robot pose
fix args type

2020-06-13 03:57 UTC, gunjanpatil commented on pybotic/worlds.py
> +    @classmethod
fix inheritance

2020-06-13 03:57 UTC, gunjanpatil commented on tests/test_Continous3D_Static.py
> +            this is will check all the valid cases
fix grammar

2020-06-13 03:57 UTC, gunjanpatil commented on tests/test_Continous3D_Static.py
> +    def setUp(self):
add docstring

2020-06-13 03:57 UTC, gunjanpatil commented on tests/test_Continous3D_Static.py
> +                                    self.start, self.goal)
Test constructor

2020-06-13 03:57 UTC, gunjanpatil commented on tests/test_Continous3D_Static.py
> +        self.assertIsInstance(self.c, Continous3D_Static)
test constructor

2020-06-13 03:57 UTC, gunjanpatil commented on tests/test_Continous3D_Static.py
> +            assert all(np.equal(a[key], b[key]))
move to test utils

2020-06-13 03:57 UTC, gunjanpatil commented on tests/test_Continous3D_Static.py
> +
comments

2020-06-13 03:57 UTC, gunjanpatil commented on tests/test_Continous3D_Static.py
> +            assert all(np.equal(a[key], b[key]))
use unit test aserts

2020-06-13 04:16 UTC, gunjanpatil commented on pybotic/worlds.py
> +                raise ValueError(f"wrong shape {shape_}")
Allow empty obstacles

2020-06-15 07:02 UTC, 00arun00 commented on tests/test_Continous3D_Static.py
> +            assert all(np.equal(a[key], b[key]))
removed since no longer needed

2020-06-15 07:03 UTC, 00arun00 commented on tests/test_Continous3D_Static.py
> +        self.assertIsInstance(self.c, Continous3D_Static)
done

2020-06-15 07:03 UTC, 00arun00 commented on tests/test_Continous3D_Static.py
> +                                    self.start, self.goal)
done

2020-06-15 07:04 UTC, 00arun00 commented on tests/test_Continous3D_Static.py
> +    def setUp(self):
done

2020-06-15 09:18 UTC, gunjanpatil requested changes

2020-06-15 09:18 UTC, gunjanpatil commented on pybotic/worlds.py
> +    """
add comments for args

2020-06-15 09:18 UTC, gunjanpatil commented on pybotic/worlds.py
> +@dataclass
make class frozen

2020-06-15 09:18 UTC, gunjanpatil commented on pybotic/worlds.py
> +            start = Point3D.create_from_iter(np.zeros((3, 1)))
no need

2020-06-15 09:29 UTC, gunjanpatil approved these changes

2020-06-15 09:29 UTC, merged